version: '3.5'
services:
  db:
    container_name: "sfef_db"
    image: "mongo:4.0"
    ports:
      - "27217:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  server:
    container_name: "sfef_server"
    build: ./packages/api
    ports:
      - "4221:4221"
    depends_on:
      - db

